### ISSUE TITLE
cantaloupe.properties.tmpl-dev is not valid for current master (5.*)

### ISSUE THREAD

**Issue by aindlq** [UCLALibrary/docker-cantaloupe#115]
Apparently https://github.com/UCLALibrary/docker-cantaloupe/blob/main/src/main/docker/configs/cantaloupe.properties.tmpl-dev is using properties for cantaloupe 4.* not for 5.*, as result some env variables have no effect with the dev build, e.g `CANTALOUPE_MAX_SCALE`.

**Comment by ksclarke** [comment]
Ah, yes, thanks. We had not originally planned to continue the dev build once we moved to v.5 so never updated that. I'll update it.

**Comment by ksclarke** [comment]
The PR for this: #116

I'll have to manually push to DockerHub once this is approved because we don't have our dev build CD workflow set up any more.

**Comment by ksclarke** [comment]
The updated Docker image is on DockerHub now: https://hub.docker.com/layers/155259647/uclalibrary/cantaloupe/latest-dev/images/sha256-2623cfc69777fa2e7b1af8d50887882cb1ace2e7ad00ac8ba02e83a9d68bab1a?context=repo
